### ISSUE TITLE
`gin`中间件中的`trace`提取问题

### ISSUE THREAD

**Issue by x-lambda** [yeqown/opentelemetry-quake#1]
hi，请教一下在gin的中间件中
https://github.com/yeqown/opentelemetry-quake/blob/main/contrib/gin/server.go#L74
假设这里客户端通过otel sdk inject一堆trace信息过来，中间件里面是如果提取的？以及如果没取到怎么办？

**Comment by yeqown** [comment]
Q: 如何提取? (了解下 propagator 的作用)
A: https://github.com/yeqown/opentelemetry-quake/blob/e3f10d573eaa7dd93abfb7eb0cfb6c45a22dcb1c/contrib/gin/server.go#L76-L78

Q: 没有取到会怎么办？（看一下 otel Tracing 的API）
A: https://github.com/yeqown/opentelemetry-quake/blob/e3f10d573eaa7dd93abfb7eb0cfb6c45a22dcb1c/contrib/gin/server.go#L80-L82

我这里只是在我的场景里为了简化各种框架中的中间件，而整合了一下API，你直接看otel的 tracing API 足以
